languages = {
    "en": "English",
    "en-US": "English (United States)",
    "en-GB": "English (United Kingdom)",
    "en-AU": "English (Australia)",
    "en-CA": "English (Canada)",
    "en-IN": "English (India)",
    "en-NZ": "English (New Zealand)",
    "en-SG": "English (Singapore)",
    "en-ZA": "English (South Africa)",
    "es": "Spanish",
    "es-ES": "Spanish (Spain)",
    "es-MX": "Spanish (Mexico)",
    "fr": "French",
    "fr-FR": "French (France)",
    "de": "German",
    "de-DE": "German (Germany)",
    "zh": "Chinese",
    "zh-CN": "Chinese (China)",
    "zh-TW": "Chinese (Taiwan)",
    "ja": "Japanese",
    "ja-JP": "Japanese (Japan)",
    "ru": "Russian",
    "ru-RU": "Russian (Russia)",
    "ar": "Arabic",
    "ar-SA": "Arabic (Saudi Arabia)",
    "hi": "Hindi",
    "hi-IN": "Hindi (India)",
    "pt": "Portuguese",
    "pt-PT": "Portuguese (Portugal)",
    "pt-BR": "Portuguese (Brazil)",
    "it": "Italian",
    "it-IT": "Italian (Italy)",
    "ko": "Korean",
    "ko-KR": "Korean (South Korea)",
    "tr": "Turkish",
    "tr-TR": "Turkish (Turkey)",
    "nl": "Dutch",
    "nl-NL": "Dutch (Netherlands)",
    "sv": "Swedish",
    "sv-SE": "Swedish (Sweden)",
    "no": "Norwegian",
    "no-NO": "Norwegian (Norway)",
    "da": "Danish",
    "da-DK": "Danish (Denmark)",
    "fi": "Finnish",
    "fi-FI": "Finnish (Finland)",
    "pl": "Polish",
    "pl-PL": "Polish (Poland)",
    "uk": "Ukrainian",
    "uk-UA": "Ukrainian (Ukraine)",
    "he": "Hebrew",
    "he-IL": "Hebrew (Israel)",
    "el": "Greek",
    "el-GR": "Greek (Greece)",
    "cs": "Czech",
    "cs-CZ": "Czech (Czech Republic)",
    "hu": "Hungarian",
    "hu-HU": "Hungarian (Hungary)",
    "ro": "Romanian",
    "ro-RO": "Romanian (Romania)",
    "th": "Thai",
    "th-TH": "Thai (Thailand)",
    "vi": "Vietnamese",
    "vi-VN": "Vietnamese (Vietnam)",
    "id": "Indonesian",
    "id-ID": "Indonesian (Indonesia)",
    "ms": "Malay",
    "ms-MY": "Malay (Malaysia)",
    "bg": "Bulgarian",
    "bg-BG": "Bulgarian (Bulgaria)",
    "sk": "Slovak",
    "sk-SK": "Slovak (Slovakia)",
    "sl": "Slovenian",
    "sl-SI": "Slovenian (Slovenia)",
    "hr": "Croatian",
    "hr-HR": "Croatian (Croatia)",
    "sr": "Serbian",
    "sr-RS": "Serbian (Serbia)",
    "lt": "Lithuanian",
    "lt-LT": "Lithuanian (Lithuania)",
    "lv": "Latvian",
    "lv-LV": "Latvian (Latvia)",
    "et": "Estonian",
    "et-EE": "Estonian (Estonia)",
    "fa": "Persian",
    "fa-IR": "Persian (Iran)",
    "ur": "Urdu",
    "ur-PK": "Urdu (Pakistan)",
    "bn": "Bengali",
    "bn-BD": "Bengali (Bangladesh)",
    "ta": "Tamil",
    "ta-IN": "Tamil (India)",
    "te": "Telugu",
    "te-IN": "Telugu (India)",
    "ml": "Malayalam",
    "ml-IN": "Malayalam (India)",
    "kn": "Kannada",
    "kn-IN": "Kannada (India)",
    "gu": "Gujarati",
    "gu-IN": "Gujarati (India)",
    "mr": "Marathi",
    "mr-IN": "Marathi (India)",
    "sw": "Swahili",
    "sw-KE": "Swahili (Kenya)",
    "af": "Afrikaans",
    "af-ZA": "Afrikaans (South Africa)",
    "is": "Icelandic",
    "is-IS": "Icelandic (Iceland)",
    "mt": "Maltese",
    "mt-MT": "Maltese (Malta)",
    "ga": "Irish",
    "ga-IE": "Irish (Ireland)",
    "cy": "Welsh",
    "cy-GB": "Welsh (United Kingdom)",
    "eu": "Basque",
    "eu-ES": "Basque (Spain)",
    "ca": "Catalan",
    "ca-ES": "Catalan (Spain)",
    "gl": "Galician",
    "gl-ES": "Galician (Spain)",
    "hy": "Armenian",
    "hy-AM": "Armenian (Armenia)",
    "ka": "Georgian",
    "ka-GE": "Georgian (Georgia)",
    "kk": "Kazakh",
    "kk-KZ": "Kazakh (Kazakhstan)",
    "uz": "Uzbek",
    "uz-UZ": "Uzbek (Uzbekistan)",
    "az": "Azerbaijani",
    "az-AZ": "Azerbaijani (Azerbaijan)",
    "mn": "Mongolian",
    "mn-MN": "Mongolian (Mongolia)",
    "my": "Burmese",
    "my-MM": "Burmese (Myanmar)",
    "km": "Khmer",
    "km-KH": "Khmer (Cambodia)",
    "lo": "Lao",
    "lo-LA": "Lao (Laos)",
    "si": "Sinhala",
    "si-LK": "Sinhala (Sri Lanka)",
    "am": "Amharic",
    "am-ET": "Amharic (Ethiopia)",
    "yo": "Yoruba",
    "yo-NG": "Yoruba (Nigeria)",
    "ig": "Igbo",
    "ig-NG": "Igbo (Nigeria)",
    "ha": "Hausa",
    "ha-NG": "Hausa (Nigeria)",
    "zu": "Zulu",
    "zu-ZA": "Zulu (South Africa)",
    "xh": "Xhosa",
    "xh-ZA": "Xhosa (South Africa)",
    "bs": "Bosnian",
    "bs-BA": "Bosnian (Bosnia and Herzegovina)",
    "mk": "Macedonian",
    "mk-MK": "Macedonian (North Macedonia)",
    "sq": "Albanian",
    "sq-AL": "Albanian (Albania)",
    "sr-Latn": "Serbian (Latin)",
    "ba": "Bashkir",
    "be": "Belarusian",
    "tt": "Tatar",
    "la": "Latin",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "ca": "Catalan",
    "ky": "Kyrgyz",
    "mo": "Moldavian"
}


def get_language(code: str) -> str:
    return languages.get(code, "Language not found")


def(main):
    code = event.get("Language")
    get_language(code)


if __name__ == "__main__":
    main()
